### ISSUE TITLE
Implement Text Summarization Using Seq2Seq with Attention

### ISSUE THREAD

**Issue by FakhirK90** [FakhirK90/ai-projects#19]
We need to create a sequence-to-sequence (Seq2Seq) model with attention for text summarization. The goal is to input a long piece of text and produce a concise summary using a neural network-based approach.

**Tasks:**

- Implement a Seq2Seq model with attention using Keras and TensorFlow.
- Train the model on a text dataset like Gigaword or any other summarization dataset.
- Evaluate the performance using ROUGE scores.

**Requirements:**

- Use Keras for building the Seq2Seq model.
- Implement attention mechanism within the model.
- Provide code to preprocess the dataset (tokenization, padding).
- Include training logs and evaluation using ROUGE or BLEU scores.

**Comment by VadisettyRahul** [comment]
@FakhirK90 please assign to me.

**Comment by FakhirK90** [comment]
@VadisettyRahul assign to you.
