### ISSUE TITLE
Build a Sentiment Analysis Model Using LSTM for Text Data

### ISSUE THREAD

**Issue by FakhirK90** [FakhirK90/ai-projects#23]
We aim to develop a sentiment analysis model using Long Short-Term Memory (LSTM) networks to classify text data into positive or negative sentiments. The model should take a sentence or a review as input and output the sentiment.

**Tasks:**

- Implement an LSTM-based sentiment analysis model using Keras and TensorFlow.
- Train the model on a sentiment analysis dataset (e.g., IMDb movie reviews).
- Evaluate the model’s accuracy and provide visualizations for model performance.
- Provide a prediction function to classify the sentiment of new text inputs.

**Requirements:**

- Use Keras for building the LSTM model.
- Preprocess the text data (tokenization, padding).
- Include code for model training, evaluation, and visualization.
- Provide instructions for using the model to classify new sentences.

**Comment by VadisettyRahul** [comment]
@FakhirK90 please assign to me.

**Comment by FakhirK90** [comment]
@VadisettyRahul assign to you.
