### ISSUE TITLE
Add Random Forest Model for Diabetes Prediction

### ISSUE THREAD

**Issue by FakhirK90** [FakhirK90/ai-projects#4]
The model in diabetes_model.py uses Logistic Regression. We want to explore if a Random Forest model can improve the accuracy of predictions.

**Tasks:**

- Implement a Random Forest classifier in the diabetes_model.py file.
- Evaluate its accuracy and confusion matrix.
- Compare the performance of the Random Forest model with the existing Logistic Regression model.

**Requirements:**

- Follow the structure of the current code.
- Ensure the Random Forest model code is properly documented.
- Add any necessary imports and dependencies.

**Comment by Mubashir-Ul-Hassan** [comment]
@FakhirK90 please assign to me as that I have an experience in this.
