### ISSUE TITLE
Add Data Visualization for Feature Distribution

### ISSUE THREAD

**Issue by FakhirK90** [FakhirK90/ai-projects#6]
To better understand the dataset, we want to visualize the distribution of features (e.g., glucose levels, BMI, age) for individuals with and without diabetes.

**Tasks:**

- Add data visualizations to the project using libraries like matplotlib or seaborn.
- Create plots for key features (e.g., glucose, insulin, BMI) and compare their distributions between diabetic and non-diabetic individuals.
- Ensure the plots are well-labeled and easy to understand.

**Requirements:**

- Use matplotlib or seaborn for the visualizations.
- Add the visualization code to a separate file (visualization.py).
- Document the visualizations and their significance in the README.

**Comment by Mubashir-Ul-Hassan** [comment]
@FakhirK90 please assign to me.
